<div class="container login">
  <div class= "col-md-6 col-md-offset-3 well">
    <form class="form" action="/login" method="post">
      <div class="form-group">
        <label for="username">Username </label>
        <input type="text" class= "form-control" name="username" id="username" placeholder="Username">
      </div>

      <div class="form-group">
        <label for="password">Password </label>
        <input type="text" class= "form-control" name="password" id="password" placeholder="Password">
      </div>

      <div class="form-group">
        <input type="submit" value="Login" class="btn btn-lg btn-primary">
      </div>
    </form>
  </div>
</div>
